# Generated by Django 2.0.5 on 2018-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='no-image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(default='no-image'),
        ),
    ]
