# Generated by Django 2.0.5 on 2018-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180602_0656'),
    ]

    operations = [
    ]
