# Generated by Django 2.0.5 on 2018-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180606_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_url',
            field=models.URLField(default='no-url', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
